#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
# Edited by leonarven                                                          #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CFLAGS = -Wall `sdl-config --cflags` -std=c++11 -std=gnu++11 -O2
LIB = -lGL -lGLU
LDFLAGS = `sdl-config --libs` -s
OBJDIR= obj
OUT = 3Dlife
OBJ = $(OBJDIR)/main.o

all: before out after

before:
	test -d $(OBJDIR) || mkdir -p $(OBJDIR)

after:

out: before $(OBJ)
	g++ -o $(OUT) $(OBJ)  $(LDFLAGS) $(LIB)

$(OBJDIR)/main.o: main.cpp
	g++ $(CFLAGS) -c main.cpp -o $(OBJDIR)/main.o

clean:
	rm -f $(OBJ) $(OUT)
	rm -rf bin
	rm -rf $(OBJDIR)
